<?xml version="1.0" encoding="utf-8"?><Database Name="THI_THDC" Class="ThiTHDCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MAYTINH-BSL3CDR;Initial Catalog=THI_THDC;Integrated Security=True;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="QL_ThiTracNghiemv2.Properties.Settings" SettingsPropertyName="THI_THDCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CauHoi" Member="CauHois">
    <Type Name="CauHoi">
      <Column Name="MaCH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DapanA" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DapanB" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DapanC" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DapanD" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LoaiCauHoi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DapanDung" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Choice" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoThe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LopSH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diem" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
</Database>