#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_ThiTracNghiemv2.View
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="THI_THDC")]
	public partial class ThiTHDCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ThiTHDCDataContext() : 
				base(global::QL_ThiTracNghiemv2.Properties.Settings.Default.THI_THDCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ThiTHDCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThiTHDCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThiTHDCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ThiTHDCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CauHoi> CauHois
		{
			get
			{
				return this.GetTable<CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CauHoi")]
	public partial class CauHoi
	{
		
		private int _MaCH;
		
		private string _NoiDung;
		
		private string _DapanA;
		
		private string _DapanB;
		
		private string _DapanC;
		
		private string _DapanD;
		
		private bool _LoaiCauHoi;
		
		private string _DapanDung;
		
		private string _Choice;
		
		public CauHoi()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCH", DbType="Int NOT NULL")]
		public int MaCH
		{
			get
			{
				return this._MaCH;
			}
			set
			{
				if ((this._MaCH != value))
				{
					this._MaCH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this._NoiDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapanA", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string DapanA
		{
			get
			{
				return this._DapanA;
			}
			set
			{
				if ((this._DapanA != value))
				{
					this._DapanA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapanB", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DapanB
		{
			get
			{
				return this._DapanB;
			}
			set
			{
				if ((this._DapanB != value))
				{
					this._DapanB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapanC", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DapanC
		{
			get
			{
				return this._DapanC;
			}
			set
			{
				if ((this._DapanC != value))
				{
					this._DapanC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapanD", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DapanD
		{
			get
			{
				return this._DapanD;
			}
			set
			{
				if ((this._DapanD != value))
				{
					this._DapanD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiCauHoi", DbType="Bit NOT NULL")]
		public bool LoaiCauHoi
		{
			get
			{
				return this._LoaiCauHoi;
			}
			set
			{
				if ((this._LoaiCauHoi != value))
				{
					this._LoaiCauHoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapanDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DapanDung
		{
			get
			{
				return this._DapanDung;
			}
			set
			{
				if ((this._DapanDung != value))
				{
					this._DapanDung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Choice", DbType="NVarChar(50)")]
		public string Choice
		{
			get
			{
				return this._Choice;
			}
			set
			{
				if ((this._Choice != value))
				{
					this._Choice = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien
	{
		
		private int _STT;
		
		private int _SoThe;
		
		private string _HoTen;
		
		private System.DateTime _NgaySinh;
		
		private string _LopSH;
		
		private System.Nullable<double> _Diem;
		
		public SinhVien()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoThe", DbType="Int NOT NULL")]
		public int SoThe
		{
			get
			{
				return this._SoThe;
			}
			set
			{
				if ((this._SoThe != value))
				{
					this._SoThe = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this._NgaySinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LopSH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LopSH
		{
			get
			{
				return this._LopSH;
			}
			set
			{
				if ((this._LopSH != value))
				{
					this._LopSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float")]
		public System.Nullable<double> Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this._Diem = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
